version: '3'

services:

  docker:
    image: docker:dind
    privileged: true
    networks:
      - frontend
    expose:
      - 2375

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - redisdb
      - docker
    environment:
      - AG_REDIS_HOST=redisdb
      - AG_REDIS_PORT=6379
      - DJANGO_SECRET_KEY=$pwx4e7xd*yd^j!cbura7kz9+)99idd-@iyn@d(%onmyz$xcmr
      - DJANGO_CONFIGURATION=Dev
      - DJANGO_SETTINGS_MODULE=simple_edu.settings
      - DOCKER_HOST=tcp://docker:2375
    ports:
      - "8000:8000"
    networks:
      - frontend
    privileged: true
    links:
      - docker

  redisdb:
    image: redis
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - frontend

networks:
    frontend:
volumes:
    redis_data:
